const types = {
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  LOAD_MENU: 'LOAD_MENU',
  SET_USER_VO: 'SET_USER_VO',
  UPDATE_USER_VO: 'UPDATE_USER_VO',
  SET_BREADCRUMB_ITEMS: 'SET_BREADCRUMB_ITEMS',
  SAVE_APP_ENV: 'SAVE_APP_ENV',
  SAVE_APP_ID: 'SAVE_APP_ID',
    GET_CAR_ENTERPRISE:'GET_CAR_ENTERPRISE',
};

export default types
